# Site settings - {{ site.* }}
name: brasskazoo
description: > # this means to ignore newlines until next property:
  Real-life adventures in Software and Build Engineering
meta_description: "Will Dampney, Real-life adventures in Software and Build Engineering"

markdown: redcarpet
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.brasskazoo.com'
google_analytics: 'UA-31903273-1'

# Details for the RSS feed generator
url:            'http://blog.brasskazoo.com'
author:         'Will Dampney'
author_tag:		'Software and Cloud Engineer'
rss_path: '/rss'
rss_name: 'feed.xml'

# permalink
permalink:		'/:year/:month/:title.html'

# Internal nav
nav:
  main:
    blog: "/"
    topics: "/topics"
    about: "/about"
