# Site settings
title: brasskazoo
email: will@brasskazoo.com
description: > # this means to ignore newlines until "baseurl:"
  Real-life adventures in Software and Build Engineering
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.brasskazoo.com" # the base hostname & protocol for your site
twitter_username: brasskazoo
github_username:  brasskazoo

# Build settings
markdown: kramdown
